"""sync models with real schema

Revision ID: 6ec5d2479849
Revises: 
Create Date: 2026-03-12 20:53:43.685494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec5d2479849'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('jti', sa.String(length=255), nullable=False),
    sa.Column('fecha_revocacion', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.create_index(op.f('ix_token_blacklist_jti'), 'token_blacklist', ['jti'], unique=True)
    op.add_column('auditoria', sa.Column('descripcion', sa.Text(), nullable=True))
    op.alter_column('auditoria', 'evento',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('auditoria', 'tipo_auditoria',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('auditoria', 'url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('idx_auditoria_usuario'), table_name='auditoria')
    op.create_index(op.f('ix_auditoria_id'), 'auditoria', ['id'], unique=False)
    op.drop_constraint(op.f('fk_auditoria_usuario'), 'auditoria', type_='foreignkey')
    op.create_foreign_key(None, 'auditoria', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('equipos', 'codigo_barras_equipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('equipos', 'nombre',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('equipos', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('equipos', 'tipo_equipo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.drop_constraint(op.f('equipos_codigo_barras_equipo_key'), 'equipos', type_='unique')
    op.drop_index(op.f('idx_equipo_estudiante'), table_name='equipos')
    op.drop_index(op.f('idx_equipo_usuario'), table_name='equipos')
    op.create_index(op.f('ix_equipos_codigo_barras_equipo'), 'equipos', ['codigo_barras_equipo'], unique=True)
    op.create_index(op.f('ix_equipos_id'), 'equipos', ['id'], unique=False)
    op.drop_constraint(op.f('fk_equipo_usuario'), 'equipos', type_='foreignkey')
    op.drop_constraint(op.f('fk_equipo_estudiante'), 'equipos', type_='foreignkey')
    op.create_foreign_key(None, 'equipos', 'usuarios', ['usuario_registra'], ['id'])
    op.create_foreign_key(None, 'equipos', 'estudiantes', ['estudiante_id'], ['id'])
    op.alter_column('estudiantes', 'codigo_barras',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('estudiantes', 'nombre',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('estudiantes', 'ficha',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               nullable=False)
    op.alter_column('estudiantes', 'documento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('estudiantes_codigo_barras_key'), 'estudiantes', type_='unique')
    op.drop_constraint(op.f('estudiantes_documento_key'), 'estudiantes', type_='unique')
    op.drop_index(op.f('idx_estudiante_usuario'), table_name='estudiantes')
    op.create_index(op.f('ix_estudiantes_codigo_barras'), 'estudiantes', ['codigo_barras'], unique=True)
    op.create_index(op.f('ix_estudiantes_documento'), 'estudiantes', ['documento'], unique=True)
    op.create_index(op.f('ix_estudiantes_id'), 'estudiantes', ['id'], unique=False)
    op.drop_constraint(op.f('fk_estudiante_usuario'), 'estudiantes', type_='foreignkey')
    op.create_foreign_key(None, 'estudiantes', 'usuarios', ['usuario_crea'], ['id'])
    op.drop_index(op.f('idx_mov_equipo'), table_name='movimientos')
    op.drop_index(op.f('idx_mov_estudiante'), table_name='movimientos')
    op.drop_index(op.f('idx_mov_usuario'), table_name='movimientos')
    op.create_index(op.f('ix_movimientos_id'), 'movimientos', ['id'], unique=False)
    op.drop_constraint(op.f('fk_mov_estudiante'), 'movimientos', type_='foreignkey')
    op.drop_constraint(op.f('fk_mov_equipo'), 'movimientos', type_='foreignkey')
    op.drop_constraint(op.f('fk_mov_usuario'), 'movimientos', type_='foreignkey')
    op.create_foreign_key(None, 'movimientos', 'estudiantes', ['estudiante_id'], ['id'])
    op.create_foreign_key(None, 'movimientos', 'equipos', ['equipo_id'], ['id'])
    op.create_foreign_key(None, 'movimientos', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('roles', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('roles', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('usuarios', 'documento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('usuarios', 'correo',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=100),
               nullable=False)
    op.alter_column('usuarios', 'contrasena',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index(op.f('idx_usuario_rol'), table_name='usuarios')
    op.drop_constraint(op.f('usuarios_documento_key'), 'usuarios', type_='unique')
    op.create_index(op.f('ix_usuarios_documento'), 'usuarios', ['documento'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.drop_constraint(op.f('fk_usuario_rol'), 'usuarios', type_='foreignkey')
    op.create_foreign_key(None, 'usuarios', 'roles', ['rol_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='foreignkey')
    op.create_foreign_key(op.f('fk_usuario_rol'), 'usuarios', 'roles', ['rol_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_documento'), table_name='usuarios')
    op.create_unique_constraint(op.f('usuarios_documento_key'), 'usuarios', ['documento'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_usuario_rol'), 'usuarios', ['rol_id'], unique=False)
    op.alter_column('usuarios', 'contrasena',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('usuarios', 'correo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('usuarios', 'documento',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.alter_column('roles', 'descripcion',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('roles', 'nombre',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'movimientos', type_='foreignkey')
    op.drop_constraint(None, 'movimientos', type_='foreignkey')
    op.drop_constraint(None, 'movimientos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_mov_usuario'), 'movimientos', 'usuarios', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_mov_equipo'), 'movimientos', 'equipos', ['equipo_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_mov_estudiante'), 'movimientos', 'estudiantes', ['estudiante_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_movimientos_id'), table_name='movimientos')
    op.create_index(op.f('idx_mov_usuario'), 'movimientos', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_mov_estudiante'), 'movimientos', ['estudiante_id'], unique=False)
    op.create_index(op.f('idx_mov_equipo'), 'movimientos', ['equipo_id'], unique=False)
    op.drop_constraint(None, 'estudiantes', type_='foreignkey')
    op.create_foreign_key(op.f('fk_estudiante_usuario'), 'estudiantes', 'usuarios', ['usuario_crea'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_estudiantes_id'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_documento'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_codigo_barras'), table_name='estudiantes')
    op.create_index(op.f('idx_estudiante_usuario'), 'estudiantes', ['usuario_crea'], unique=False)
    op.create_unique_constraint(op.f('estudiantes_documento_key'), 'estudiantes', ['documento'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('estudiantes_codigo_barras_key'), 'estudiantes', ['codigo_barras'], postgresql_nulls_not_distinct=False)
    op.alter_column('estudiantes', 'documento',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('estudiantes', 'ficha',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('estudiantes', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('estudiantes', 'codigo_barras',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'equipos', type_='foreignkey')
    op.drop_constraint(None, 'equipos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_equipo_estudiante'), 'equipos', 'estudiantes', ['estudiante_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_equipo_usuario'), 'equipos', 'usuarios', ['usuario_registra'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_equipos_id'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_codigo_barras_equipo'), table_name='equipos')
    op.create_index(op.f('idx_equipo_usuario'), 'equipos', ['usuario_registra'], unique=False)
    op.create_index(op.f('idx_equipo_estudiante'), 'equipos', ['estudiante_id'], unique=False)
    op.create_unique_constraint(op.f('equipos_codigo_barras_equipo_key'), 'equipos', ['codigo_barras_equipo'], postgresql_nulls_not_distinct=False)
    op.alter_column('equipos', 'tipo_equipo',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('equipos', 'descripcion',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('equipos', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('equipos', 'codigo_barras_equipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(None, 'auditoria', type_='foreignkey')
    op.create_foreign_key(op.f('fk_auditoria_usuario'), 'auditoria', 'usuarios', ['usuario_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_auditoria_id'), table_name='auditoria')
    op.create_index(op.f('idx_auditoria_usuario'), 'auditoria', ['usuario_id'], unique=False)
    op.alter_column('auditoria', 'url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('auditoria', 'tipo_auditoria',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('auditoria', 'evento',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('auditoria', 'descripcion')
    op.drop_index(op.f('ix_token_blacklist_jti'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
