"""sync models with real schema

Revision ID: 72c2df07f0e7
Revises: 6ec5d2479849
Create Date: 2026-03-12 21:06:32.559281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c2df07f0e7'
down_revision: Union[str, Sequence[str], None] = '6ec5d2479849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auditoria', 'evento',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('auditoria', 'tipo_auditoria',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('auditoria', 'url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_auditoria_usuario_id'), 'auditoria', ['usuario_id'], unique=False)
    op.drop_column('auditoria', 'descripcion')
    op.alter_column('equipos', 'codigo_barras_equipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('equipos', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('equipos', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('equipos', 'tipo_equipo',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_index(op.f('ix_equipos_codigo_barras_equipo'), table_name='equipos')
    op.create_index(op.f('ix_equipos_estudiante_id'), 'equipos', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_equipos_usuario_registra'), 'equipos', ['usuario_registra'], unique=False)
    op.create_unique_constraint(None, 'equipos', ['codigo_barras_equipo'])
    op.alter_column('estudiantes', 'codigo_barras',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('estudiantes', 'documento',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('estudiantes', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('estudiantes', 'ficha',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_index(op.f('ix_estudiantes_codigo_barras'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_documento'), table_name='estudiantes')
    op.create_index(op.f('ix_estudiantes_usuario_crea'), 'estudiantes', ['usuario_crea'], unique=False)
    op.create_unique_constraint(None, 'estudiantes', ['codigo_barras'])
    op.create_unique_constraint(None, 'estudiantes', ['documento'])
    op.create_index(op.f('ix_movimientos_equipo_id'), 'movimientos', ['equipo_id'], unique=False)
    op.create_index(op.f('ix_movimientos_estudiante_id'), 'movimientos', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_movimientos_usuario_id'), 'movimientos', ['usuario_id'], unique=False)
    op.alter_column('roles', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('roles', 'descripcion',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('usuarios', 'documento',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('usuarios', 'correo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True)
    op.alter_column('usuarios', 'contrasena',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_usuarios_documento'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_rol_id'), 'usuarios', ['rol_id'], unique=False)
    op.create_unique_constraint(None, 'usuarios', ['documento'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.drop_index(op.f('ix_usuarios_rol_id'), table_name='usuarios')
    op.create_index(op.f('ix_usuarios_documento'), 'usuarios', ['documento'], unique=True)
    op.alter_column('usuarios', 'contrasena',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('usuarios', 'correo',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('usuarios', 'documento',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('roles', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('roles', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_index(op.f('ix_movimientos_usuario_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_estudiante_id'), table_name='movimientos')
    op.drop_index(op.f('ix_movimientos_equipo_id'), table_name='movimientos')
    op.drop_constraint(None, 'estudiantes', type_='unique')
    op.drop_constraint(None, 'estudiantes', type_='unique')
    op.drop_index(op.f('ix_estudiantes_usuario_crea'), table_name='estudiantes')
    op.create_index(op.f('ix_estudiantes_documento'), 'estudiantes', ['documento'], unique=True)
    op.create_index(op.f('ix_estudiantes_codigo_barras'), 'estudiantes', ['codigo_barras'], unique=True)
    op.alter_column('estudiantes', 'ficha',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('estudiantes', 'nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('estudiantes', 'documento',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('estudiantes', 'codigo_barras',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'equipos', type_='unique')
    op.drop_index(op.f('ix_equipos_usuario_registra'), table_name='equipos')
    op.drop_index(op.f('ix_equipos_estudiante_id'), table_name='equipos')
    op.create_index(op.f('ix_equipos_codigo_barras_equipo'), 'equipos', ['codigo_barras_equipo'], unique=True)
    op.alter_column('equipos', 'tipo_equipo',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('equipos', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('equipos', 'nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('equipos', 'codigo_barras_equipo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.add_column('auditoria', sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_auditoria_usuario_id'), table_name='auditoria')
    op.alter_column('auditoria', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('auditoria', 'tipo_auditoria',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('auditoria', 'evento',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###
